version: '3.9'
services:
  web3-server:
    container_name: web3-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - VAULT_HOST=211.73.81.185:30305
      - VAULT_TOKEN=s.WH1QFR0GzWQieaG43ZhgIoiw
      - ETH_NODE_HOST=211.73.81.45:8545
      - CHAIN_ID=86532
      - GAS_LIMIT=1071003
      - GAS_PRICE=25000
      - MINER_PRIVATE_KEY=0x08a1aa1bef5948f97454d6ca9c4b96c07b23a666267b3c5457040510ac19cdb0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web3-server.rule=Host(`211.73.81.185`)&&(PathPrefix(`/api`)||PathPrefix(`/swagger-ui`))"
      - "traefik.http.routers.web3-server.tls=true"
      - "traefik.http.routers.web3-server.tls.certresolver=production"
    ports:
      - 8001:8000
    entrypoint: cargo run dev
    networks:
      - web3-dev
  web3-mongo:
    container_name: web3-mongo
    image: mongo:5.0.9
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=web3-dev
      - MONGO_INITDB_USERNAME=user
      - MONGO_INITDB_PASSWORD=pass
    ports:
      - 27018:27017
    volumes:
      - ./docker/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/mongo/db:/data/db
    networks:
      - web3-dev
networks:
  web3-dev:
    external:
      name: traefik
    