version: '3.9'
services:
  traefik:
    container_name: traefik
    image: traefik:2.7
    volumes:
      -  ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/log:/var/log/traefik/
      - ./docker/traefik/acme:/etc/traefik/certs
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    networks:
      - traefik
networks:
  traefik:
    name: traefik
    driver: bridge
