GET http://127.0.0.1:8000/api HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDk5MTk0Nzl9.sCGF1SVELJDkF4D3s0UBlhmVaYwQrldrhNVb9JTxfFE

###
POST http://127.0.0.1:8000/api/signup HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn1@gmail.com",
    "password": "asd123"
}

###
POST http://20.109.112.166:8001/api/signin HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn123@gmail.com",
    "password": "asd123"
}

###

GET http://127.0.0.1:8000/api/hash HTTP/1.1
Content-Type: application/json

{
    "raw_data":"test123456"
}

###

POST http://127.0.0.1:8000/api/hash HTTP/1.1
Content-Type: application/json

{
    "address": "0xeA4c45d4e0f2517016774f7ce45B03606B753aE8",
    "private_key": "0x911f12fb0246378dc32cc675b0535b3056d8c166b156d08bc5f29c968e4585b6",
    "hash_data": "85777F270AD7CF2A790981BBAE3C4E484A1DC55E24A77390D692FBF1CFFA12FA"
}

###

GET http://127.0.0.1:8000/api/contract/isIssuer HTTP/1.1
Content-Type: application/json

{
    "address": "0x0a3bbbf6596eb5671df75e14bbc629eebbb9c23c",
    "account_name": "duaifzn123@gmail.com",
    "target_address": "0xFB4c5d29B78083905617092A105b41Cd327365Ef"
}

###0x3ea02c2c76bced0e4c51bebb9aabd6cb66b28c07682be996341920126a389cca
###
POST http://127.0.0.1:8000/api/contract/addIssuer HTTP/1.1
Content-Type: application/json

{
    "address": "0x096A37b3Ca5d96d3b251825291a10a92164cAcAf",
    "account_name": "duaifzn123@gmail.com",
    "target_address": "0xed2d160c638ebe1c3c3d120fcc0df8719d7c685e"
}

###
POST http://127.0.0.1:8000/api/contract/notarizeHash HTTP/1.1
Content-Type: application/json

{
    "address": "0xb9ee715cdfca2fe5fdbaab9feace3b6f7bb11f4f",
    "account_name": "duaifzn123@gmail.com",
    "key": "test32111",
    "value": "test456"
}

###
GET http://127.0.0.1:8000/api/contract/getHash HTTP/1.1
Content-Type: application/json

{
    "address": "0xb9ee715cdfca2fe5fdbaab9feace3b6f7bb11f4f",
    "account_name": "duaifzn123@gmail.com",
    "key": "test32111"
}

###
POST http://20.109.112.166:8001/api/contract/deployContract HTTP/1.1
Content-Type: application/json

{
    "account_name": "duaifzn123@gmail.com"
}
###0xc7ed5464e24ec0685e8b26605ef26e85f60c1dbf7e61da3fcd1cba168a6216f5