GET http://127.0.0.1:8000/api HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjAifQ.eyJleHAiOjE2NTM1NTI0Mzh9.iAFhYaOmKgC4ElIasqeW-SWdiKqe-iYTLkvJdGvYGk0A76plhMXUgu3L-uPORYHmyptgo6r4HfdCnqK9qFdCmw

###
POST http://127.0.0.1:8000/api/signup HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn1@gmail.com",
    "password": "asd123"
}

###
POST http://127.0.0.1:8000/api/signin HTTP/1.1
Content-Type: application/json

{
    "email":"duaifzn12345@gmail.com",
    "password": "123"
}

###
POST http://127.0.0.1:8000/api/admin/money/transfer HTTP/1.1
# Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjAifQ.eyJleHAiOjE2NTM1NTI0Mzh9.iAFhYaOmKgC4ElIasqeW-SWdiKqe-iYTLkvJdGvYGk0A76plhMXUgu3L-uPORYHmyptgo6r4HfdCnqK9qFdCmw
Content-Type: application/json

{
    "to_account_name": "duaifzn12345@gmail.com"
}

###
GET http://127.0.0.1:8000/api/balance?account_name=duaifzn12345@gmail.com HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjAifQ.eyJleHAiOjE2NTM1NTI0Mzh9.iAFhYaOmKgC4ElIasqeW-SWdiKqe-iYTLkvJdGvYGk0A76plhMXUgu3L-uPORYHmyptgo6r4HfdCnqK9qFdCmw

###

GET http://127.0.0.1:8000/api/hash HTTP/1.1
Content-Type: application/json

{
    "raw_data":"test123456"
}

###

POST http://127.0.0.1:8000/api/hash HTTP/1.1
Content-Type: application/json

{
    "address": "0xeA4c45d4e0f2517016774f7ce45B03606B753aE8",
    "private_key": "0x911f12fb0246378dc32cc675b0535b3056d8c166b156d08bc5f29c968e4585b6",
    "hash_data": "85777F270AD7CF2A790981BBAE3C4E484A1DC55E24A77390D692FBF1CFFA12FA"
}

###

GET http://127.0.0.1:8000/api/contract/isIssuer?contract_address=0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8&account_name=duaifzn123@gmail.com&issuer_address=0x87bbeD49992ca50Ac38Fc3fD893Bd1102F3052a1 HTTP/1.1

//duaifzn123@gmail.com 0xFB4c5d29B78083905617092A105b41Cd327365Ef
//duaifzn1@gmail.com 0x87bbeD49992ca50Ac38Fc3fD893Bd1102F3052a1
    //"tx_address": "0x849cbe34fcfcfeddf070768c235a3108c0d856ef502418f9455e112b2230ef73",
    //"contract_address": "0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8"
###
POST http://127.0.0.1:8000/api/contract/addIssuer HTTP/1.1
Content-Type: application/json

{
    "contract_address": "0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8",
    "account_name": "duaifzn123@gmail.com",
    "issuer_address": "0x87bbeD49992ca50Ac38Fc3fD893Bd1102F3052a1"
}

###
POST http://127.0.0.1:8000/api/contract/notarizeHash HTTP/1.1
Content-Type: application/json

{
    "contract_address": "0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8",
    "account_name": "duaifzn123@gmail.com",
    "key": "test3211111",
    "value": "test456"
}

###0x4af7110aa9d5f18ee5f1cd65d4fedeb4cad867af2e9c65c1a7fb8f358f41eff0
PATCH http://127.0.0.1:8000/api/contract/revokeHash HTTP/1.1
Content-Type: application/json

{
    "contract_address": "0xcbd60da5f6dc1641c666a12e231d585379cc0e03",
    "account_name": "duaifzn1@gmail.com",
    "key": "test32111"
}

###
GET http://127.0.0.1:8000/api/contract/isRevoked?contract_address=0xcbd60da5f6dc1641c666a12e231d585379cc0e03&account_name=duaifzn123@gmail.com&key=test32111 HTTP/1.1

###
GET http://127.0.0.1:8000/api/contract/getHash?contract_address=0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8&account_name=duaifzn123@gmail.com&key=test3211111 HTTP/1.1

###
DELETE http://127.0.0.1:8000/api/contract/delIssuer HTTP/1.1
Content-Type: application/json

{
    "contract_address": "0xcbd60da5f6dc1641c666a12e231d585379cc0e03",
    "account_name": "duaifzn123@gmail.com",
    "target_address": "0x87bbeD49992ca50Ac38Fc3fD893Bd1102F3052a1"
}

###
PATCH http://127.0.0.1:8000/api/contract/transferOwnership HTTP/1.1
Content-Type: application/json

{
    "contract_address": "0xcbd60da5f6dc1641c666a12e231d585379cc0e03",
    "account_name": "duaifzn123@gmail.com",
    "target_address": "0x87bbeD49992ca50Ac38Fc3fD893Bd1102F3052a1"
}
###
POST http://127.0.0.1:8000/api/contract/deployContract HTTP/1.1
Content-Type: application/json

{
    "account_name": "duaifzn123@gmail.com"
}
###0xc7ed5464e24ec0685e8b26605ef26e85f60c1dbf7e61da3fcd1cba168a6216f5

GET http://127.0.0.1:8000/api/contract/log/blockhash?contract_address=0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8=blockhash=0xb531bc2a581d9dc2c476c55d3f9251a3e104b4db0c9d66da04564fc73000d711 HTTP/1.1

###0xb531bc2a581d9dc2c476c55d3f9251a3e104b4db0c9d66da04564fc73000d711

GET http://127.0.0.1:8000/api/contract/log/transaction?contract_address=0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8&tx_address=0x4af7110aa9d5f18ee5f1cd65d4fedeb4cad867af2e9c65c1a7fb8f358f41eff0 HTTP/1.1

###

POST http://127.0.0.1:8000/api/contract/log/all HTTP/1.1
Content-Type: application/json

{   
    "contract_address": "0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8"
}

###

GET http://127.0.0.1:8000/api/contract/log/event/ProofCreated?key=test3211111&contract_address=0xf1ce66ed87b9fbbfeef17789f8c1f2a7aabde7a8&start_timestamp=1653792085&end_timestamp=1653792085 HTTP/1.1

###
