version: '3.9'
services:
  ethereum-node:
    container_name: ethereum-node
    env_file:
      - .env
    build: 
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
      - PRIVATECHAIN_PATH=${PRIVATECHAIN_PATH}
      - NETWORK_ID=${NETWORK_ID}
    ports:
      - '30303:30303'
      - '8545:8545'
    volumes:
      - ./docker/keystore:/tmp/privatechain/keystore